spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/maqta
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: car-park-availability-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        topics:
          park-availability-topic: park_availability_topic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8081

app:
  feature:
    radius: 5000 # Define a search radius in meters